# Generated by Django 4.2.4 on 2023-08-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=30)),
                ('phon', models.CharField(max_length=12)),
                ('emaill', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
