# Generated by Django 4.2.4 on 2023-08-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_attendance_remove_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='timein',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='timeout',
        ),
    ]
