# Generated by Django 4.2.4 on 2023-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_phone_user_timein_rename_email_user_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timein',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='timeout',
            field=models.TimeField(blank=True),
        ),
    ]
