# Generated by Django 4.2.4 on 2023-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_user_timein_alter_user_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timein',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='timeout',
            field=models.DateTimeField(),
        ),
    ]
